### ISSUE TITLE
The linux build is broken

### ISSUE THREAD

**Issue by francisdb** [francisdb/pinmame-tester#3]
First issue, bindgen generates different code for mac arm64 compared to linux x64
see https://github.com/rust-lang/rust-bindgen/issues/2631

Second issue, at this moment libpinmame does not generate a static lib and I have not found a way to make this work dynamically.

Some pointers from @jsm174 

> https://github.com/vpinball/pinmame/blob/master/cmake/libpinmame/CMakeLists_linux-x64.txt
> so it looks like I never made the static version of this in linux
> if you look at this version:
> 
> https://github.com/vpinball/pinmame/blob/master/cmake/libpinmame/CMakeLists_osx-arm64.txt
> if(BUILD_SHARED)  if(BUILD_STATIC)
> I would need to update all them to support static libs.. It was so long ago
> https://github.com/vpinball/pinmame/pull/105
> 
> ...
> 
> only ios and macos use the static
> linux and android use so
> but if you want static, you could modify cmake with the same patches
> 
> ...
> 
> I see, and you copy those somewhere the binary will find them?
> 
> ...
>
> well, I remove the RPATH, so it will look in executable directory
> but that is what LD_LIBRARY_PATH env var does in linux

**Comment by jsm174** [comment]
> First issue, bindgen generates different code for mac arm64 compared to linux x64
see https://github.com/rust-lang/rust-bindgen/issues/2631

I have no experience with rust, so I'm not sure why the bindings would be different.

> Second issue, at this moment libpinmame does not generate a static lib and I have not found a way to make this work dynamically.

There is nothing wrong with the Linux build. It's used by several different projects. The title of this PR is misleading.

Yes, the CMake file for linux does not have an option to make a static lib, but that doesn't mean the build is broke.

**Comment by francisdb** [comment]
the pinmame-tester linux/win build is currently broken and disabled on github ci

Guess I need to spend some more time to get this to work but not in a hurry.

**Comment by jsm174** [comment]
Sorry, I'm not following:

https://github.com/vpinball/pinmame/actions/runs/6119865452

This is all reporting okay?

**Comment by francisdb** [comment]
wrong project 😉
https://github.com/francisdb/pinmame-tester/actions

**Comment by jsm174** [comment]
ahhh... okay.. My apologies 😄  I was looking at this on my phone.
